[package]
name = "news-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ureq = "2.5.0"
dotenv = "0.15.0"
serde = { version = "1.0.127", features=["derive"] }
serde_json = "1.0.66"
